### ISSUE TITLE
Add documentation 

### ISSUE THREAD

**Issue by sanny-io** [sanny-io/react-appwrite#5]
This will help developers understand the functions more with the provided intellisense. Links to the relevant Appwrite documentation would also be great.

`useAccount` has decent documentation so far.

![](https://i.imgur.com/lW8XEFO.png)

**Comment by probablyArth** [comment]
I would like to start working on it!

**Comment by sanny-io** [comment]
@probablyArth Awesome 😄

I have assigned you. Any area you want to document, feel free to open a pull request, but I'm not expecting you to do all of it haha. There's a whole lot of stuff that needs it, so whatever you can do is good bro 👍

**Comment by probablyArth** [comment]
should close this one considering every function is documented?

**Comment by sanny-io** [comment]
Yes sir you are right.
